### ISSUE TITLE
Facepunch ware error

### ISSUE THREAD

**Issue by Cata2806** [Thadah/GarryWare13#1]
After you pick up files and throw them to folder, you'll get "mails" and if you throw them back to facepunch, it will get away from mails and you can't complete the minigame.

[ERROR] gamemodes/garryware13/gamemode/wareminigames/facepunch.lua:239: attempt to perform arithmetic on a nil value
1. v - gamemodes/garryware13/gamemode/wareminigames/facepunch.lua:239
   1. unknown - lua/includes/modules/hook.lua:84

**Comment by lyxara** [comment]
`vel = vel:Normalize() * ((speed - self.BVelocity) * 0.7 + self.BVelocity)`
The method `Vector:Normalize` is just for changing the current vector and it returns nothing.
If you want to return a normalized copy without affecting the original, use `Vector:GetNormalized`.
