### ISSUE TITLE
crashes the game

### ISSUE THREAD

**Issue by unek** [Thadah/GarryWare13#33]
it seems to crash the game for almost every player. no other addons/gamemodes on the server. sometimes crashes a few people at once.

the game just freezes.

**Comment by Thadah** [comment]
I believe it has to do with the vast amount of usermessages that are sent throughout the gamemode

I'm not completely sure though, but I'll see what I can do to improve performance, since the code is so old and was meant for when Garry's Mod could multithread.

**Comment by Smallinger** [comment]
yep is still on so i hope you finde a way to fix that

**Comment by Thadah** [comment]
Did you try the development branch? I didn't merge it because I wanted to fix some wares but I ended up not having time, but the branch should work fine

**Comment by Thadah** [comment]
I made a new stable release merging all the code from the development branch. 
I need testers to know if the game still breaks.
