### ISSUE TITLE
GameLength 

### ISSUE THREAD

**Issue by HarbuFP** [Thadah/GarryWare13#35]
ERROR] gamemodes/garryware13/gamemode/vgui_clockgame.lua:59: attempt to perform arithmetic on field 'GameLength' (a nil value)
1. unknown - gamemodes/garryware13/gamemode/vgui_clockgame.lua:59

**Comment by KoreanJebus** [comment]
Is this still being worked on?

**Comment by lyxara** [comment]
We're currently working on our own projects, so we don't have enough time to work on fixing these bugs. If you need us to fix it, we'll try to find a gap in the agenda to do it.

**Comment by KoreanJebus** [comment]
That would be awesome. And is there a way to play this gamemode with the bug?

**Comment by lyxara** [comment]
We were working on an improved version of the gamemode, but we stopped because of the studies. When we can, we're going to try to finish it.

**Comment by KoreanJebus** [comment]
Awesome! Thanks for the response!

**Comment by Thadah** [comment]
I'll try to make a workaround or something to get rid of the problem until we can provide a better framework for this gamemode

**Comment by Thadah** [comment]
I released a workaround but since I don't know if it works and I don't like bad coding I'll leave this opened

**Comment by Thadah** [comment]
commit 313c500 is pretty much the same, but I think I will leave it like that as the bug is sporadic and doesn't happen very often
