### ISSUE TITLE
Memory Color-Numbered crates

### ISSUE THREAD

**Issue by Cata2806** [Thadah/GarryWare13#5]
You have to memorize the number's color at the beginning and after that, you have to shoot it the one that gamemode says, but there is no color

[ERROR] gamemodes/garryware13/gamemode/wareminigames/memorytriangle.lua:85: attempt to index local 'self' (a nil value)
1. unknown - gamemodes/garryware13/gamemode/wareminigames/memorytriangle.lua:85

Timer Failed! [Simple][@gamemodes/garryware13/gamemode/wareminigames/memorytriangle.lua (line 78)]

[ERROR] gamemodes/garryware13/gamemode/wareminigames/memorytriangle.lua:100: attempt to index local 'self' (a nil value)
1. unknown - gamemodes/garryware13/gamemode/wareminigames/memorytriangle.lua:100

Timer Failed! [Simple][@gamemodes/garryware13/gamemode/wareminigames/memorytriangle.lua (line 79)]

**Comment by Cyumus** [comment]
Fixed with 9a179a148e7bcdf405cae35af7ca82a714b2a9e1

**Comment by lyxara** [comment]
It seems that it has been fixed with 7e4374c07a4b74bbe143b588d4c159caa45faee3
