### ISSUE TITLE
Bumping circles Minigame

### ISSUE THREAD

**Issue by Cata2806** [Thadah/GarryWare13#6]
At the start, you have a crowbar, if you throw it away, there is no error in game but you will get this script error

Failed to load sound "weapons\flame_thrower_airblast_rocket_redirect.wav", file probably missing from disk/repository

[ERROR] gamemodes/garryware13/gamemode/wareminigames/avoidcircles.lua:79: attempt to perform arithmetic on a nil value
1. v - gamemodes/garryware13/gamemode/wareminigames/avoidcircles.lua:79
   1. unknown - lua/includes/modules/hook.lua:84

Failed to load sound "weapons\flame_thrower_airblast_rocket_redirect.wav", file probably missing from disk/repository

[ERROR] gamemodes/garryware13/gamemode/wareminigames/pickupthatcan.lua:16: attempt to index field 'Models' (a nil value)
1. FlashCans - gamemodes/garryware13/gamemode/wareminigames/pickupthatcan.lua:16
   1. Initialize - gamemodes/garryware13/gamemode/wareminigames/pickupthatcan.lua:60
   2. PickRandomGame - gamemodes/garryware13/gamemode/init.lua:156
      1. unknown - gamemodes/garryware13/gamemode/init.lua:408

**Comment by lyxara** [comment]
Fixed with 7e4374c07a4b74bbe143b588d4c159caa45faee3
